### PR TITLE
Map Location Additions

### PR DESCRIPTION
**Pull request by corian-jal**
The implementation of the campus map has been completed. It appears as if the bubbles initialized for the campus map in campus-map.component.ts are having trouble being recognized outside of it, so we request a review from the backend team in order to see if some change needs to be made with regard to interaction with the firebase.

### CODE REVIEW

**Comment by corian-jal** [comment]
After pulling from main, the workflow failed prematurely due to an error in src/app/game/game.component.ts on line 66 related to "databaseEventListener(player.getDatabasePath(), this.updatePlayerDatabase.bind(this));". This may be resolved by one of the other PRs currently in wait, specifically PR#84; when it is merged, we will pull it into this branch as well.

**Comment by corian-jal** [comment]
Correction: the error was caused by a mistake with the merge resolution. Now it should show that the campus map is failing with undefined values.

**Review by gypark23 — CHANGES_REQUESTED** [review]
Watch out when you merge the commits, especially on home.component.ts. Please accept changes from #84 and just add your edits on top of it.

**Comment by nd1az** [comment]
Yeah. I just looked over and saw that a lot of code was not accepted from only accepting incoming changes when merging. I just fixed up the issues caused by that and will now resolve the conflicts with main

**Comment by jasulcaf** [comment]
Just a note, there are bound to be even more merge issues after the most recent PRs have been pushed as well

**Comment by nd1az** [comment]
Looked over the failing test and saw that the test was trying to get hard coded information from the campus map, however all that stuff was in the onInit fn which gets data bound properties so the test wasn't going to get access to any of that information and was removed.

**Review by nd1az — APPROVED** [review]
Looks to be working, just need the bubbles that are hard coded here to be initialized before running the playerInBubble function on tick

**Review by gypark23 — APPROVED** [review]

**Review by gypark23 — APPROVED** [review]

**Pull request merged**
