### PR TITLE
Fixed the lack of map object and added game tick

### PR DESCRIPTION
**Pull request by noahklowden**
I missed these in the previous PR. All this does is add the map object and game rules to the database and also added the line for the gameTick.

### CODE REVIEW

**Review by jasulcaf — APPROVED** [review]
LGTM - Though I think that the other PR should be merged first (as that one is supposed to fix all the failing tests)

**Comment by jasulcaf** [comment]
Seems that the other PR has been merged - would do a git pull on the branch just to double check

**Review by Anna-Bele — COMMENTED** [review]
Looks good to me as well!

**Review by jasulcaf — CHANGES_REQUESTED** [review]
Tests are now failing despite passing in main

**Review by Anna-Bele — APPROVED** [review]
Lgtm!

**Pull request merged**
