### PR TITLE
Change for displaying map

### PR DESCRIPTION
**Pull request by nd1az**
I added the use of the global.playerlist to the playersBubble method so that other components can use it to retrieve the Bubble the player is currently. 
This method should now generate a list of players nearby by going through the players in the game and returning the bubble of the player given to it.

### CODE REVIEW

**Comment by Strongbrother1** [comment]
I'm not sure if you wanted me to review it now, but when I run "tns run ios" This error appears:
`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'playerInBubble' of undefined
  TypeError: Cannot read property 'playerInBubble' of undefined
  at file: src/webpack:/appGeo/src/app/map/campus-map.component.ts:326:0
  at Map.forEach (<anonymous>)
  at CampusMap.playersBubble (file: src/webpack:/appGeo/src/app/map/campus-map.component.ts:325:0)
  at CampusMap.ngOnInit (file: src/webpack:/appGeo/src/app/map/campus-map.component.ts:40:0)
  at callHook (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:2491:0)
  at callHooks (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:2460:0)
  at executeInitAndCheckHooks (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:2411:0)
  at refreshView (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:11971:0)
  at detectChangesInternal (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:13174:0)
  at RootViewRef.detectChanges (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:13686:0)`

**Comment by Strongbrother1** [comment]
Just tested, error is 
`ERROR Error: Uncaught (in promise): TypeError: pToCheck.getAliveStatus is not a function
  TypeError: pToCheck.getAliveStatus is not a function
  at CampusMap.playerInBubble (file: src/webpack:/appGeo/src/app/map/campus-map.component.ts:57:0)
  at CampusMap.playersBubble (file: src/webpack:/appGeo/src/app/map/campus-map.component.ts:329:0)
  at CampusMap.ngOnInit (file: src/webpack:/appGeo/src/app/map/campus-map.component.ts:40:0)
  at callHook (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:2491:0)
  at callHooks (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:2460:0)
  at executeInitAndCheckHooks (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:2411:0)
  at refreshView (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:11971:0)
  at detectChangesInternal (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:13174:0)
  at RootViewRef.detectChanges (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:13686:0)
  at PageRouterOutlet.activateOnGoForward (file: src/webpack:/appGeo/node_modules/@nativescript/angular/fesm2015/nativescript-angular.mjs:6700:41)`

**Comment by nd1az** [comment]
I changed the code from` pToCheck.getAliveStatus()` to `pToCheck.alive`
the rest of the code prior to line 57 had it written this way and did not pass an error, so my assumption is that it will pass this point now. 
will keep looking into it though

**Comment by Strongbrother1** [comment]
ERROR Error: Uncaught (in promise): TypeError: player.getUserID is not a function
  TypeError: player.getUserID is not a function
  at Bubble.addPlayer (file: src/webpack:/appGeo/src/app/map/map.component.ts:17:0)
  at CampusMap.playerInBubble (file: src/webpack:/appGeo/src/app/map/campus-map.component.ts:59:0)
  at CampusMap.playersBubble (file: src/webpack:/appGeo/src/app/map/campus-map.component.ts:329:0)
  at CampusMap.ngOnInit (file: src/webpack:/appGeo/src/app/map/campus-map.component.ts:40:0)
  at callHook (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:2491:0)
  at callHooks (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:2460:0)
  at executeInitAndCheckHooks (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:2411:0)
  at refreshView (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:11971:0)
  at detectChangesInternal (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:13174:0)
  at RootViewRef.detectChanges (file: src/webpack:/appGeo/node_modules/@angular/core/fesm2015/core.mjs:13686:0)

**Review by Strongbrother1 — APPROVED** [review]
tns run ios runs perfectly and "players nearby" option shows

**Pull request merged**
