### PR TITLE
Pulling/Pushing Player on Database

### LINKED ISSUE #77: Google Logins
Connect Google Logins with an actual player in the game, (Probably has to do with the player class? - Have to discuss)

### PR DESCRIPTION
**Pull request by gypark23**
Implemented a global variable that represents the actual "Player" who is running the app on the device right now. Also now Chat component can use the username retrieved from the log-in. 

Closes #77

### CODE REVIEW

**Comment by gypark23** [comment]
@jasulcaf could you check when you log in to your google account and then chat, your name appears? I checked mine and my name appears.

**Comment by jasulcaf** [comment]
> @jasulcaf could you check when you log in to your google account and then chat, your name appears? I checked mine and my name appears.

I'm currently testing

**Comment by jasulcaf** [comment]
Google Sign in Geo Mafia
Below is what I get after doing Google Sign in. It appears that the console log does get my name/information correctly, it however doesn't display on the screen (unsure if that was supposed to be intended or not)

**Comment by jasulcaf** [comment]
Also, Player Tests did not get messed up from this commit - fyi

**Comment by gypark23** [comment]
> Google Sign in Geo Mafia
> Below is what I get after doing Google Sign in. It appears that the console log does get my name/information correctly, it however doesn't display on the screen (unsure if that was supposed to be intended or not)

Yeah I didnt really update anything on screen. Can you go to chat and send some message? And see if your name appears as a sender.

**Comment by jasulcaf** [comment]
Screenshot 2022-11-20 at 5 53 15 PM
Yup, messages sent have my name on it

**Review by jasulcaf — APPROVED** [review]
There's a couple merge conflicts because of the most recent PR, but after resolving those, this looks like great progress :)

**Pull request merged**
